# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pdx
                                 A QGIS plugin
 Αυτοματοποίηση λειτουργιών πδχ
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-05
        copyright            : (C) 2025 by Takis Tsiberis
        email                : tsiberis@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pdx class from file pdx.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from ._pdx import pdx
    return pdx(iface)
